"""Guided Task Engine for the AI Assistant API.

This module provides functionality to parse, store, and manage step-by-step
instructions generated by the LLM for guided task completion.
"""

import json
import re
from typing import Dict, List, Any, Optional
import logging
import uuid
from datetime import datetime, timedelta

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Simple in-memory session store (replace with Redis or database in production)
SESSION_STORE: Dict[str, Dict[str, Any]] = {}

# Session expiration time (30 minutes)
SESSION_EXPIRATION = timedelta(minutes=30)

class GuidedTaskEngine:
    """Engine for parsing and managing guided task steps."""
    
    def __init__(self):
        """Initialize the guided task engine."""
        # Clean expired sessions periodically
        self._clean_expired_sessions()
    
    def parse_steps(self, response: str) -> List[Dict[str, Any]]:
        """Parse steps from an LLM response.
        
        Args:
            response: The raw LLM response text.
            
        Returns:
            A list of step objects.
        """
        try:
            # Try to parse JSON from the response
            parsed = self._extract_json(response)
            
            if parsed and "steps" in parsed and isinstance(parsed["steps"], list):
                # Validate and normalize steps
                steps = []
                for i, step in enumerate(parsed["steps"]):
                    # Ensure step has required fields
                    if not all(k in step for k in ["id", "title", "description"]):
                        continue
                    
                    # Normalize step
                    normalized_step = {
                        "id": step["id"],
                        "title": step["title"],
                        "description": step["description"],
                        "completed": step.get("completed", False)
                    }
                    
                    steps.append(normalized_step)
                
                return steps
            
            # If no valid steps found, try to extract steps from text
            return self._extract_steps_from_text(response)
        except Exception as e:
            logger.error(f"Error parsing steps: {e}")
            return []
    
    def store_steps(self, session_id: str, steps: List[Dict[str, Any]]) -> None:
        """Store steps for a session.
        
        Args:
            session_id: The session ID.
            steps: The list of steps.
        """
        # Create or update session
        SESSION_STORE[session_id] = {
            "steps": steps,
            "expires_at": datetime.now() + SESSION_EXPIRATION,
            "current_step": 0
        }
    
    def get_steps(self, session_id: str) -> Optional[List[Dict[str, Any]]]:
        """Get steps for a session.
        
        Args:
            session_id: The session ID.
            
        Returns:
            The list of steps, or None if session not found.
        """
        session = SESSION_STORE.get(session_id)
        
        if not session:
            return None
        
        # Update expiration
        session["expires_at"] = datetime.now() + SESSION_EXPIRATION
        
        return session["steps"]
    
    def update_step_status(self, session_id: str, step_id: str, completed: bool) -> bool:
        """Update the status of a step.
        
        Args:
            session_id: The session ID.
            step_id: The step ID.
            completed: Whether the step is completed.
            
        Returns:
            True if successful, False otherwise.
        """
        session = SESSION_STORE.get(session_id)
        
        if not session:
            return False
        
        # Update expiration
        session["expires_at"] = datetime.now() + SESSION_EXPIRATION
        
        # Find and update step
        for step in session["steps"]:
            if step["id"] == step_id:
                step["completed"] = completed
                
                # Update current step if this step was completed
                if completed:
                    current_index = next((i for i, s in enumerate(session["steps"]) if s["id"] == step_id), -1)
                    if current_index >= 0 and current_index == session["current_step"]:
                        session["current_step"] = min(current_index + 1, len(session["steps"]) - 1)
                
                return True
        
        return False
    
    def get_current_step(self, session_id: str) -> Optional[Dict[str, Any]]:
        """Get the current active step for a session.
        
        Args:
            session_id: The session ID.
            
        Returns:
            The current step, or None if session not found.
        """
        session = SESSION_STORE.get(session_id)
        
        if not session or not session["steps"]:
            return None
        
        # Update expiration
        session["expires_at"] = datetime.now() + SESSION_EXPIRATION
        
        return session["steps"][session["current_step"]]
    
    def _extract_json(self, text: str) -> Optional[Dict[str, Any]]:
        """Extract JSON from text.
        
        Args:
            text: The text to extract JSON from.
            
        Returns:
            The extracted JSON as a dictionary, or None if not found.
        """
        try:
            # Look for JSON-like structure
            start_idx = text.find('{')
            end_idx = text.rfind('}')
            
            if start_idx >= 0 and end_idx > start_idx:
                json_str = text[start_idx:end_idx + 1]
                return json.loads(json_str)
            return None
        except json.JSONDecodeError:
            return None
    
    def _extract_steps_from_text(self, text: str) -> List[Dict[str, Any]]:
        """Extract steps from plain text.
        
        Args:
            text: The text to extract steps from.
            
        Returns:
            A list of step objects.
        """
        steps = []
        
        # Look for numbered steps or bullet points
        step_patterns = [
            r'(?:^|\n)\s*(\d+)\s*\.\s*([^\n]+)(?:\n\s*([^\n]*(?:\n\s+[^\n]*)*))?',  # Numbered steps
            r'(?:^|\n)\s*[•\*\-]\s*([^\n]+)(?:\n\s*([^\n]*(?:\n\s+[^\n]*)*))?'  # Bullet points
        ]
        
        for pattern in step_patterns:
            matches = re.finditer(pattern, text, re.MULTILINE)
            
            for i, match in enumerate(matches):
                if len(match.groups()) >= 2:
                    # For numbered steps
                    if match.group(1) and match.group(1).isdigit():
                        title = match.group(2).strip()
                        description = match.group(3).strip() if len(match.groups()) > 2 and match.group(3) else ""
                    # For bullet points
                    else:
                        title = match.group(1).strip()
                        description = match.group(2).strip() if len(match.groups()) > 1 and match.group(2) else ""
                    
                    step_id = f"step{i+1}"
                    
                    steps.append({
                        "id": step_id,
                        "title": title,
                        "description": description,
                        "completed": False
                    })
        
        return steps
    
    def _clean_expired_sessions(self) -> None:
        """Clean expired sessions from the session store."""
        now = datetime.now()
        expired_sessions = []
        
        for session_id, session in SESSION_STORE.items():
            if session["expires_at"] < now:
                expired_sessions.append(session_id)
        
        for session_id in expired_sessions:
            del SESSION_STORE[session_id]